
DROP DATABASE JOBS;

CREATE DATABASE JOBS;
USE JOBS;

CREATE TABLE TIPOS_USER(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(40) NOT NULL
);
CREATE TABLE USUARIOS(
	MATRICULA VARCHAR (40)  PRIMARY KEY NOT NULL,
	NOME VARCHAR (40) NOT NULL,
	TELEFONE VARCHAR (40),
	USUARIO VARCHAR (40) NOT NULL,
	SENHA VARCHAR (40),


	TIPOS_USER INT NOT NULL,
	CONSTRAINT FK_TIPOS_USER FOREIGN KEY (TIPOS_USER) REFERENCES TIPOS_USER(ID)
);
CREATE TABLE MODALIDADES(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT ,
	NOME VARCHAR (40) NOT NULL
);
CREATE TABLE TIMES(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	PONTOS INT(10),
	NOME VARCHAR (40) NOT NULL,

	MOD_ID INT NOT NULL,
	CONSTRAINT FK_MOD_TIMES FOREIGN KEY (MOD_ID) REFERENCES MODALIDADES(ID),
	USU_ID VARCHAR (40) NOT NULL,
	CONSTRAINT FK_USU_TIMES FOREIGN KEY (USU_ID) REFERENCES USUARIOS(MATRICULA)
);
CREATE TABLE PARTICIPANTES(
	ID INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
	MATRICULA VARCHAR (20),
	NOME VARCHAR (40) NOT NULL,

	TIMES_ID INT NOT NULL,
	CONSTRAINT FK_TIMES_PART FOREIGN KEY (TIMES_ID) REFERENCES TIMES(ID)
);
insert into TIPOS_USER(NOME) values('administrador');
insert into TIPOS_USER(NOME) values('aluno');
insert into TIPOS_USER(NOME) values('professor');
insert into TIPOS_USER(NOME) values('egresso');

insert into MODALIDADES(nome) values
    ('LOL'),
    ('FIFA'),
    ('CSS'),
    ('DOMINO'),
    ('XADRES'),
    ('VOLEY'),
    ('FUTSAL');